### ISSUE TITLE
eventsを配信するapiの作成

### ISSUE THREAD

**Issue by KaiShoya** [lumbermill/events.lmlab.net#8]
index.jsonを作る

**Comment by yosei** [comment]
プロジェクトのページに最新情報を載せたいので、特定の投稿者、さらにタイトルで絞り込みたいです。

```
/events_by/3.json?title=CoderDojo
```

**Comment by yosei** [comment]
json形式の配布に対応！
http://events.lmlab.net/events_by/3.json
